//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:2.0.50727.4963
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DotNet.Common.Resources {
    using System;
    
    
    /// <summary>
    ///   强类型资源类，用于查找本地化字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class R {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal R() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DotNet.Common.Resources.R", typeof(R).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   为使用此强类型资源类的所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 不能转换成指定的类型 “{0}”. 的本地化字符串。
        /// </summary>
        internal static string Argument_CanNotConvertType {
            get {
                return ResourceManager.GetString("Argument_CanNotConvertType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 文件 “{0}” 没有扩展名。 的本地化字符串。
        /// </summary>
        internal static string Argument_FileNoExtension {
            get {
                return ResourceManager.GetString("Argument_FileNoExtension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 文件“{0}”不存在。 的本地化字符串。
        /// </summary>
        internal static string Argument_FileNotExist {
            get {
                return ResourceManager.GetString("Argument_FileNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 没有发现指定的文件。 的本地化字符串。
        /// </summary>
        internal static string Argument_FileNotFound {
            get {
                return ResourceManager.GetString("Argument_FileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 文件路径 “{0}” 不是完全限定路径。 的本地化字符串。
        /// </summary>
        internal static string Argument_FileNotFullPath {
            get {
                return ResourceManager.GetString("Argument_FileNotFullPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 类型“{0}”无效。 的本地化字符串。
        /// </summary>
        internal static string Argument_InvalidType {
            get {
                return ResourceManager.GetString("Argument_InvalidType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 语言“{0}”在已激活的语言集合中不存在。 的本地化字符串。
        /// </summary>
        internal static string Argument_LanguageNameNotExist {
            get {
                return ResourceManager.GetString("Argument_LanguageNameNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 参数 “{0}” 值不能为空。 的本地化字符串。
        /// </summary>
        internal static string ArgumentNull {
            get {
                return ResourceManager.GetString("ArgumentNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 值为空引用或零长度字符串。 的本地化字符串。
        /// </summary>
        internal static string ArgumentNull_NoText {
            get {
                return ResourceManager.GetString("ArgumentNull_NoText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 文件名为空引用或零长度字符串。 的本地化字符串。
        /// </summary>
        internal static string ArgumentNull_NoText_FileName {
            get {
                return ResourceManager.GetString("ArgumentNull_NoText_FileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 文件名不能为空。 的本地化字符串。
        /// </summary>
        internal static string ArgumentNullOrEmpty_FileName {
            get {
                return ResourceManager.GetString("ArgumentNullOrEmpty_FileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 没有发现指定文件 “{0}”。 的本地化字符串。
        /// </summary>
        internal static string ArgumentNullOrEmpty_FileNotFound {
            get {
                return ResourceManager.GetString("ArgumentNullOrEmpty_FileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 文件搜索模式不能为空。 的本地化字符串。
        /// </summary>
        internal static string ArgumentNullOrEmpty_FileSarchPattern {
            get {
                return ResourceManager.GetString("ArgumentNullOrEmpty_FileSarchPattern", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 参数不能为空。 的本地化字符串。
        /// </summary>
        internal static string ArgumentNullOrEmpty_Generic {
            get {
                return ResourceManager.GetString("ArgumentNullOrEmpty_Generic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 语言名不能为空。 的本地化字符串。
        /// </summary>
        internal static string ArgumentNullOrEmpty_LanguageName {
            get {
                return ResourceManager.GetString("ArgumentNullOrEmpty_LanguageName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 路径不能为空。 的本地化字符串。
        /// </summary>
        internal static string ArgumentNullOrEmpty_Path {
            get {
                return ResourceManager.GetString("ArgumentNullOrEmpty_Path", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 DotNet配置结点组名称不能为空。 的本地化字符串。
        /// </summary>
        internal static string ArgumentNullOrEmpty_SectionGroupName {
            get {
                return ResourceManager.GetString("ArgumentNullOrEmpty_SectionGroupName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 DotNet配置结点名称不能为空。 的本地化字符串。
        /// </summary>
        internal static string ArgumentNullOrEmpty_SectionName {
            get {
                return ResourceManager.GetString("ArgumentNullOrEmpty_SectionName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 数组参数 “{0}” 值一定不能为空引用且数组一定要包含数组项。 的本地化字符串。
        /// </summary>
        internal static string ArrayNoElements {
            get {
                return ResourceManager.GetString("ArrayNoElements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 数组 “{0}” 值不能为空引用或空数组。 的本地化字符串。
        /// </summary>
        internal static string ArrayNullOrEmpty {
            get {
                return ResourceManager.GetString("ArrayNullOrEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 [断言失败]表达式一定为true。 的本地化字符串。
        /// </summary>
        internal static string AssertExpressionTrue {
            get {
                return ResourceManager.GetString("AssertExpressionTrue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 调用类型“{0}”上的方法“{1}”失败。 的本地化字符串。
        /// </summary>
        internal static string CallMethod_MethodCallFailed {
            get {
                return ResourceManager.GetString("CallMethod_MethodCallFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 值不能为空。 的本地化字符串。
        /// </summary>
        internal static string CannotBeEmpty {
            get {
                return ResourceManager.GetString("CannotBeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 值不能为Null。 的本地化字符串。
        /// </summary>
        internal static string CannotBeNull {
            get {
                return ResourceManager.GetString("CannotBeNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 值不能转换到类型 “{0}“。 的本地化字符串。
        /// </summary>
        internal static string CanNotConvertType {
            get {
                return ResourceManager.GetString("CanNotConvertType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 集合不能为空或Null。 的本地化字符串。
        /// </summary>
        internal static string CollectionCannotBeEmptyOrNull {
            get {
                return ResourceManager.GetString("CollectionCannotBeEmptyOrNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 判断条件不为False。 的本地化字符串。
        /// </summary>
        internal static string ConditionNotFalse {
            get {
                return ResourceManager.GetString("ConditionNotFalse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 判断条件不为True。 的本地化字符串。
        /// </summary>
        internal static string ConditionNotTrue {
            get {
                return ResourceManager.GetString("ConditionNotTrue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 未能为类型 “{0}” 加载配置文件 “{1}”。 的本地化字符串。
        /// </summary>
        internal static string ConfigError_ConfigFileLoadFail {
            get {
                return ResourceManager.GetString("ConfigError_ConfigFileLoadFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 没有发现指定的配置文件“{0}”。 的本地化字符串。
        /// </summary>
        internal static string ConfigError_ConfigFileNotFound {
            get {
                return ResourceManager.GetString("ConfigError_ConfigFileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 默认的提供者“{0}”加载类型成为“{1}”时失败。 的本地化字符串。
        /// </summary>
        internal static string ConfigError_DefaultProviderLoadFail {
            get {
                return ResourceManager.GetString("ConfigError_DefaultProviderLoadFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 在配置设置中没有找到默认的提供者“{0}”。 的本地化字符串。
        /// </summary>
        internal static string ConfigError_DefaultProviderNotFound {
            get {
                return ResourceManager.GetString("ConfigError_DefaultProviderNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 文件映射关系名“{0}”在配置文件中不能重复。 的本地化字符串。
        /// </summary>
        internal static string ConfigError_DuplicateFileMapping {
            get {
                return ResourceManager.GetString("ConfigError_DuplicateFileMapping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 在配置类 &quot;{0}&quot; 上没有设置配置属性 ”{1}“。 的本地化字符串。
        /// </summary>
        internal static string ConfigError_NoConfigAttribute {
            get {
                return ResourceManager.GetString("ConfigError_NoConfigAttribute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 类型“{0}”没有包含ConfigAttribute属性。 的本地化字符串。
        /// </summary>
        internal static string ConfigError_NoConfigFileAttribute {
            get {
                return ResourceManager.GetString("ConfigError_NoConfigFileAttribute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 类型“{0}”没有包含ConfigFileSectionAttribute属性。 的本地化字符串。
        /// </summary>
        internal static string ConfigError_NoConfigFileSectionAttribute {
            get {
                return ResourceManager.GetString("ConfigError_NoConfigFileSectionAttribute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 类型“{0}”没有包含ConfigFileSectionGroupAttribute属性。 的本地化字符串。
        /// </summary>
        internal static string ConfigError_NoConfigFileSectionGroupAttribute {
            get {
                return ResourceManager.GetString("ConfigError_NoConfigFileSectionGroupAttribute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 提供者“{0}”加载类型成为“{1}”时失败。 的本地化字符串。
        /// </summary>
        internal static string ConfigError_ProviderLoadFail {
            get {
                return ResourceManager.GetString("ConfigError_ProviderLoadFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 在配置设置中没有找到提供者“{0}”。 的本地化字符串。
        /// </summary>
        internal static string ConfigError_ProviderNotFound {
            get {
                return ResourceManager.GetString("ConfigError_ProviderNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Service {0} NotFound 的本地化字符串。
        /// </summary>
        internal static string ConfigError_ServiceNotFound {
            get {
                return ResourceManager.GetString("ConfigError_ServiceNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 配置文件 “{0}” 不能解析成 &quot;{1}&quot;。 的本地化字符串。
        /// </summary>
        internal static string ConfigFileNotResolved {
            get {
                return ResourceManager.GetString("ConfigFileNotResolved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 没有指定和配置对应的文件。 的本地化字符串。
        /// </summary>
        internal static string ConfigFileNotSpecified {
            get {
                return ResourceManager.GetString("ConfigFileNotSpecified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 配置源“{0}”没有找到。 的本地化字符串。
        /// </summary>
        internal static string ConfigSourceNotFound {
            get {
                return ResourceManager.GetString("ConfigSourceNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 加密算法“{0}”不支持“{1}”数据模式。 的本地化字符串。
        /// </summary>
        internal static string Crypto_DataModeNotSupport {
            get {
                return ResourceManager.GetString("Crypto_DataModeNotSupport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 没有发现目录“{0}”。 的本地化字符串。
        /// </summary>
        internal static string DirectoryNotFound_DirectoryName {
            get {
                return ResourceManager.GetString("DirectoryNotFound_DirectoryName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 和配置文件 &quot;{0}&quot; SectionName: {1} 对应的配置不能正常解析。 的本地化字符串。
        /// </summary>
        internal static string DotNetConfigCannotBeResolved {
            get {
                return ResourceManager.GetString("DotNetConfigCannotBeResolved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 重复的键值。 的本地化字符串。
        /// </summary>
        internal static string DuplicateKey_Default {
            get {
                return ResourceManager.GetString("DuplicateKey_Default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 重复的键值“{0}”。 的本地化字符串。
        /// </summary>
        internal static string DuplicateKey_DefaultFormat {
            get {
                return ResourceManager.GetString("DuplicateKey_DefaultFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 枚举值 &quot;{0}&quot; 无效。 的本地化字符串。
        /// </summary>
        internal static string Enum_IllegalVal {
            get {
                return ResourceManager.GetString("Enum_IllegalVal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 系统环境变量访问被拒绝。 的本地化字符串。
        /// </summary>
        internal static string EnvironmentVariablesDeniedToRead {
            get {
                return ResourceManager.GetString("EnvironmentVariablesDeniedToRead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 SqlCommand类型的命令是必须的。 的本地化字符串。
        /// </summary>
        internal static string ExceptionCommandNotSqlCommand {
            get {
                return ResourceManager.GetString("ExceptionCommandNotSqlCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 值为空引用或零长度字符串。 的本地化字符串。
        /// </summary>
        internal static string ExceptionEmptyText {
            get {
                return ResourceManager.GetString("ExceptionEmptyText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 异常事件抛出失败。 的本地化字符串。
        /// </summary>
        internal static string ExceptionEventRaisingFailed {
            get {
                return ResourceManager.GetString("ExceptionEventRaisingFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 提供的参数的数量和存储过程提供的参数不匹配。 的本地化字符串。
        /// </summary>
        internal static string ExceptionMessageParameterMatchFailure {
            get {
                return ResourceManager.GetString("ExceptionMessageParameterMatchFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 至少要初始化一个命令。 的本地化字符串。
        /// </summary>
        internal static string ExceptionMessageUpdateDataSetArgumentFailure {
            get {
                return ResourceManager.GetString("ExceptionMessageUpdateDataSetArgumentFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 更新数据库记录失败。 的本地化字符串。
        /// </summary>
        internal static string ExceptionMessageUpdateDataSetRowFailure {
            get {
                return ResourceManager.GetString("ExceptionMessageUpdateDataSetRowFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Parameter discovery is not supported for connections using GenericDatabase. You must specify the parameters explicitly, or configure the connection to use a type deriving from Database that supports parameter discovery. 的本地化字符串。
        /// </summary>
        internal static string ExceptionParameterDiscoveryNotSupportedOnGenericDatabase {
            get {
                return ResourceManager.GetString("ExceptionParameterDiscoveryNotSupportedOnGenericDatabase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 用来映射结果的用户特定的表名数组长度不能为空。  的本地化字符串。
        /// </summary>
        internal static string ExceptionTableNameArrayEmpty {
            get {
                return ResourceManager.GetString("ExceptionTableNameArrayEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 在对象“{0}”上没有找到字段“{1}”。 的本地化字符串。
        /// </summary>
        internal static string FieldNotFound {
            get {
                return ResourceManager.GetString("FieldNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 文件集合中没有文件存在。 的本地化字符串。
        /// </summary>
        internal static string FileArrayEmpty {
            get {
                return ResourceManager.GetString("FileArrayEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 文件 “{0}” 加载失败。 的本地化字符串。
        /// </summary>
        internal static string FileLoadFail {
            get {
                return ResourceManager.GetString("FileLoadFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Xml文件 “{0}” 加载失败。 的本地化字符串。
        /// </summary>
        internal static string FileLoadFail_Xml {
            get {
                return ResourceManager.GetString("FileLoadFail_Xml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 文件 “{0}” 不存在。 的本地化字符串。
        /// </summary>
        internal static string FileNotFound {
            get {
                return ResourceManager.GetString("FileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 文件路径 “{0}” 不是完全限定路径。 的本地化字符串。
        /// </summary>
        internal static string FileNotFullPath {
            get {
                return ResourceManager.GetString("FileNotFullPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 没有文件合并。 的本地化字符串。
        /// </summary>
        internal static string FileNotMerged {
            get {
                return ResourceManager.GetString("FileNotMerged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 文件不全部存在，所有文件 &quot;{1}&quot; 中以下文件 &quot;{2}&quot; 不存在。 的本地化字符串。
        /// </summary>
        internal static string FilesNotFullFound {
            get {
                return ResourceManager.GetString("FilesNotFullFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 “{0}”不是一个有效的布尔字符串。 的本地化字符串。
        /// </summary>
        internal static string Format_BadBoolean {
            get {
                return ResourceManager.GetString("Format_BadBoolean", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 不能读取内嵌属性。Error message: {0} 的本地化字符串。
        /// </summary>
        internal static string IntrinsicPropertyError {
            get {
                return ResourceManager.GetString("IntrinsicPropertyError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Permission for UnmanagedCode is not available. 的本地化字符串。
        /// </summary>
        internal static string IntrinsicPropertyNoUnmanagedCodePermissionError {
            get {
                return ResourceManager.GetString("IntrinsicPropertyNoUnmanagedCodePermissionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 在对象“{0}”上没有找到字段“{1}”。 的本地化字符串。
        /// </summary>
        internal static string InvalidOperation_FieldNotFound {
            get {
                return ResourceManager.GetString("InvalidOperation_FieldNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 在对象“{0}”上没有找到属性“{1}”。 的本地化字符串。
        /// </summary>
        internal static string InvalidOperation_PropertyNotFound {
            get {
                return ResourceManager.GetString("InvalidOperation_PropertyNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 类型名 &quot;{0}&quot; 不能被正确解析。 的本地化字符串。
        /// </summary>
        internal static string InvalidTypeName {
            get {
                return ResourceManager.GetString("InvalidTypeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 日志提供者“{0}”加载失败。 的本地化字符串。
        /// </summary>
        internal static string LoggerLoadFail {
            get {
                return ResourceManager.GetString("LoggerLoadFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 日志提供者“{0}”没有找到。 的本地化字符串。
        /// </summary>
        internal static string LoggerNotFound {
            get {
                return ResourceManager.GetString("LoggerNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 默认的日志提供者有指定，但指定类型不匹配。 的本地化字符串。
        /// </summary>
        internal static string LoggingSettings_DefaultProviderNotConfig {
            get {
                return ResourceManager.GetString("LoggingSettings_DefaultProviderNotConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 默认的日志提供者没有指定。 的本地化字符串。
        /// </summary>
        internal static string LoggingSettings_DefaultProviderNotSpecified {
            get {
                return ResourceManager.GetString("LoggingSettings_DefaultProviderNotSpecified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 默认的日志提供者“{0}”类型加载失败。 的本地化字符串。
        /// </summary>
        internal static string LoggingSettings_DefaultProviderTypeLoadFail {
            get {
                return ResourceManager.GetString("LoggingSettings_DefaultProviderTypeLoadFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 日志设置没有配置。 的本地化字符串。
        /// </summary>
        internal static string LoggingSettingsNotConfig {
            get {
                return ResourceManager.GetString("LoggingSettingsNotConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 调用类型“{0}”上的方法“{1}”失败。 的本地化字符串。
        /// </summary>
        internal static string MethodCallFailed {
            get {
                return ResourceManager.GetString("MethodCallFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 值必须在 {0} 和 {1} 之间。 的本地化字符串。
        /// </summary>
        internal static string MustBeBetween {
            get {
                return ResourceManager.GetString("MustBeBetween", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 值一定要大于 {0}。 的本地化字符串。
        /// </summary>
        internal static string MustBeGreaterThan {
            get {
                return ResourceManager.GetString("MustBeGreaterThan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 值一定要大小或等于 {0}。 的本地化字符串。
        /// </summary>
        internal static string MustBeGreaterThanOrEqualTo {
            get {
                return ResourceManager.GetString("MustBeGreaterThanOrEqualTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 值一定要大小或等于零。 的本地化字符串。
        /// </summary>
        internal static string MustBeGreaterThanOrEqualToZero {
            get {
                return ResourceManager.GetString("MustBeGreaterThanOrEqualToZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 值一定要大小零。 的本地化字符串。
        /// </summary>
        internal static string MustBeGreaterThanZero {
            get {
                return ResourceManager.GetString("MustBeGreaterThanZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 值一定要小于 {0}。 的本地化字符串。
        /// </summary>
        internal static string MustBeLessThan {
            get {
                return ResourceManager.GetString("MustBeLessThan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 值一定要小于或等于 {0}。 的本地化字符串。
        /// </summary>
        internal static string MustBeLessThanOrEqualTo {
            get {
                return ResourceManager.GetString("MustBeLessThanOrEqualTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 类型“{0}”没有实现参数为 &quot;{1}&quot; 的构造函数。 的本地化字符串。
        /// </summary>
        internal static string NotImplemented_ConstructorsWithParameters {
            get {
                return ResourceManager.GetString("NotImplemented_ConstructorsWithParameters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 类型“{0}”没有实现默认的空构造函数。 的本地化字符串。
        /// </summary>
        internal static string NotImplemented_DefaultConstructorMethod {
            get {
                return ResourceManager.GetString("NotImplemented_DefaultConstructorMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 类型“{0}”上没有实现方法“{1}”。 的本地化字符串。
        /// </summary>
        internal static string NotImplemented_Method {
            get {
                return ResourceManager.GetString("NotImplemented_Method", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 类型“{0}”上没有实现方法 “{1}({2})”。 的本地化字符串。
        /// </summary>
        internal static string NotImplemented_MethodWithParameters {
            get {
                return ResourceManager.GetString("NotImplemented_MethodWithParameters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 不支持带参数的构造函数。 的本地化字符串。
        /// </summary>
        internal static string NotSupported_ConstructorsWithParameters {
            get {
                return ResourceManager.GetString("NotSupported_ConstructorsWithParameters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 不支持对类型“{0}”的转换。 的本地化字符串。
        /// </summary>
        internal static string NotSupported_ConvensionType {
            get {
                return ResourceManager.GetString("NotSupported_ConvensionType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 password=,pwd= 的本地化字符串。
        /// </summary>
        internal static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 在对象“{0}”上没有找到属性“{1}”。 的本地化字符串。
        /// </summary>
        internal static string PropertyNotFound {
            get {
                return ResourceManager.GetString("PropertyNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 序列化字段 &quot;{0}&quot; 不存在。 的本地化字符串。
        /// </summary>
        internal static string Serialization_MissField {
            get {
                return ResourceManager.GetString("Serialization_MissField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 字符串不能为空或Null。 的本地化字符串。
        /// </summary>
        internal static string StringCannotBeEmptyOrNull {
            get {
                return ResourceManager.GetString("StringCannotBeEmptyOrNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 参数 “{0}” 值 “{1}” 不能为空引用或零长度字符串(清除字符串前后空白字符串)。 的本地化字符串。
        /// </summary>
        internal static string StringNullOrEmpty {
            get {
                return ResourceManager.GetString("StringNullOrEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 类型“{0}”必须为枚举类型。 的本地化字符串。
        /// </summary>
        internal static string TypeIsNotEnumType {
            get {
                return ResourceManager.GetString("TypeIsNotEnumType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 类型“{0}”加载失败。 的本地化字符串。
        /// </summary>
        internal static string TypeLoadFail {
            get {
                return ResourceManager.GetString("TypeLoadFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 类型 “{0}” 不是所期望的类型 “{0}”。 的本地化字符串。
        /// </summary>
        internal static string UnexpectedType {
            get {
                return ResourceManager.GetString("UnexpectedType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 user id=,uid= 的本地化字符串。
        /// </summary>
        internal static string UserName {
            get {
                return ResourceManager.GetString("UserName", resourceCulture);
            }
        }
    }
}
